/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int g_data1 = -4000;
int g_data2 = 5000;



int main(void)
{
    /* Loop forever */
	printf("The size of char is %u\n",sizeof(char));
	printf("The size of int is %u\n",sizeof(int));
	printf("The size of short is %u\n",sizeof(short));
	printf("The size of long is %u\n",sizeof(long));
	printf("The size of long long is %u\n",sizeof(long long));
	printf("The size of float is %u\n",sizeof(float));
	for(;;);
}
